version: "3"

services:
  reverse-proxy:
    build:
      context: "./reverse-proxy"
    ports:
      - 80:9000
    depends_on:
      - api-server
      - client-server

  api-server:
    build:
      context: "./api"
    ports:
      - 5000:3000

  client-server:
    build:
      context: "./client"
    ports:
      - 4000:5000
